export const paramsMapping: Record<string, string[]> = {
  voltage: [
    'V_L1_N',
    'V_L2_N',
    'V_L3_N',
    'VN_AVG',
    'V_L1_L2',
    'V_L2_L3',
    'V_L3_L1',
    'VL_AVG',
    'FR',
    'FT',
  ],

  flowMeter: ['FR', 'FT'],
  current: ['CURR_L1', 'CURR_L2', 'CURR_L3', 'AMP_AVG'],
  power: ['TOTAL_PF'],
  activePower: ['P1_KW', 'P2_KW', 'P3_KW', 'TOTAL_KW'],
  reactivePower: ['TOTAL_KVAR'],
  apparentPower: ['TOTAL_KVA'],
  energy: [
    'IMP_KWH',
    'EXP_KWH',
    'IMP_KVARH',
    'EXP_KVARH',
    'IMP_KVAH',
    'EXP_KVAH',
    'DEL_ACTIVE_ENERGY',
    'REACTIVE_TOTAL',
    'APPERENT_TOTAL',
  ],
  frequency: ['F'],
  thd: [
    'THD_V1',
    'THD_V2',
    'THD_V3',
    'THD_V_Avg',
    'THD_I1',
    'THD_I2',
    'THD_I3',
    'THD_I_Avg',
  ],
};
